apiVersion: v1
kind: Service # Create service
metadata:
  name: odoo # Sets the service name
  labels:
    app: odoo # Defines app to create service for
spec:
  type: NodePort # Sets the service type
  ports:
    - port: 8069 # Sets the port to run the postgres application
  selector:
    app: odoo
