apiVersion: v1
kind: ConfigMap
metadata:
  name: odoo-config
data:
  odoo.conf: |
    [options]
    data_dir = /var/lib/odoo
    admin_passwd = r00t2

    db_host = postgres.odoo
    db_port = 5432
    db_user = odoo
    db_password = odoo

    log_level = debug

# db_host = [Postgres Service].[Namespace]
